### ISSUE TITLE
What do you want out of teachers_pet?

### ISSUE THREAD

**Issue by tarebyte** [education/teachers_pet#107]
Hi Everyone,

I'm currently working on proposals for [Google Summer of Code 2015](http://www.google-melange.com/gsoc/homepage/google/gsoc2015), and one of the open source projects I would like to contribute more to would be teachers_pet!

If you have pain points or features that you would like to see, please comment on this issue or feel free to email me at mark@marktareshawty.com

**Comment by kelleydv** [comment]
One thing I'd like to see is a command like `check_progress` where I could quickly identify who has been making commits and who hasn't for a particular assignment and/or for a list of usernames.  This would allow me to motivate where it's needed most.

There are many ways I could imagine this being implemented.  I'm curious if anyone else is interested in something similar.

**Comment by sdexter72** [comment]
@kelleydv, a student of mine and I are working on something like this for his independent study project (just started about a month ago). We'd be happy to talk about what we're doing and/or how it *should* be done...

**Comment by mikehelmick** [comment]
If you are in need of additional mentors for the project, I will be available. (I wrote the first version and am also a Googler, but that second part probably doesn't help much)

**Comment by tarebyte** [comment]
@mikehelmick I'd love to get your feedback on my gsoc issue github/gsoc/issues/21

**Comment by PeterDaveHello** [comment]
Oops, I opened a issue here #112, sorry for the inconvenience caused.
