### ISSUE TITLE
command nnexport not found

### ISSUE THREAD

**Issue by eduOSS** [education/teachers_pet#118]
Hi, there.

When I try to set the TEACHERS_PET_GITHUB_TOKEN, running `source ~./bash_profile`, I hit a snag: `nnexport: command not found` 

Could you tell me why? Thanks very much. 

Warmly,
Leo

**Comment by afeld** [comment]
My guess is that you have a type in your `~/.bash_profile`...`nnexport` instead of `export`. Feel free to reopen if that's not the case!

**Comment by eduOSS** [comment]
Below is the content of `~/.bash_profile`(token has been changed):  
`\n\nexport TEACHERS_PET_GITHUB=b80lj3b4276943d2a9d2e10a8247654sjmfe0ec1babjh`  
So, could you please help me correct it?

**Comment by afeld** [comment]
What operating system are you running? Mind running the following and pasting the output here?

```bash
printf "foo\n\nbar\n"
```

I think `echo` doesn't interpret `\n`s the same on all *-nix operating systems. Anyway, just remove the two `\n\n`'s at the beginning, run `source ~/.bash_profile`, and you should be good to go.

**Comment by eduOSS** [comment]
So it's been guaranteed that an other err I met has nothing to do with this issue now. Thanks.
